### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sorafujiyama** [sorafujiyama/furima--29708-#10]
#URL
https://furima-29708.herokuapp.com/

#Basic認証のIDとパスワード
ID: sora
PW: 0202

#出品者用のメールアドレスとパスワード
メールアドレス: sample123@sample.com
PW: yasu0202

#購入者用のメールアドレスとパスワード
メールアドレス: sample22@sample.com
PW: yasu0202

#購入用カードの番号・期限・セキュリティコード
カード番号: 4242424242424242
有効期限: 12/24
CVC: 123

**Comment by oshim0115** [comment]
藤山さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・商品出品時、発送元の地域についての情報が必須になっていますが、発送元を記入せずとも出品できる状態になっています。こちら発送元の地域についての記入がない場合、出品できないように修正をお願いします。
<img width="470" alt="スクリーンショット 2020-09-28 10 30 49" src="https://user-images.githubusercontent.com/57244739/94382011-19781180-0176-11eb-9469-02933dcdd0eb.png">


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sorafujiyama** [comment]
修正しました

**Comment by vesper1102609** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
